//! Where memory lives. Every path comes from an injected [`Dirs`], never from the environment
//! deep in the code; only memoryd's `main` reads the XDG variables.

use crate::ids::TopicPath;
use porter_core::SpaceId;
use std::path::{Path, PathBuf};

/// The four XDG roots memory uses.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Dirs {
    data_home: PathBuf,
    cache_home: PathBuf,
    config_home: PathBuf,
    runtime_dir: PathBuf,
}

impl Dirs {
    /// The roots: `$XDG_DATA_HOME`, `$XDG_CACHE_HOME`, `$XDG_CONFIG_HOME`, `$XDG_RUNTIME_DIR`.
    pub fn new(
        data_home: PathBuf,
        cache_home: PathBuf,
        config_home: PathBuf,
        runtime_dir: PathBuf,
    ) -> Self {
        Self {
            data_home,
            cache_home,
            config_home,
            runtime_dir,
        }
    }

    /// `<data>/quire/memory`.
    pub fn memory(&self) -> PathBuf {
        self.data_home.join("quire").join("memory")
    }

    /// `<data>/quire/memory/spaces.toml`.
    pub fn spaces_toml(&self) -> PathBuf {
        self.memory().join("spaces.toml")
    }

    /// The desktop-level log: Space created or deleted, checkpoint anchors.
    pub fn system_events_db(&self) -> PathBuf {
        self.memory().join("system").join("events.db")
    }

    /// One Space's directory.
    pub fn space(&self, space: &SpaceId) -> PathBuf {
        self.memory().join(space.as_str())
    }

    /// One Space's event log.
    pub fn events_db(&self, space: &SpaceId) -> PathBuf {
        self.space(space).join("events.db")
    }

    /// The topic files' directory.
    pub fn facts(&self, space: &SpaceId) -> PathBuf {
        self.space(space).join("facts")
    }

    /// The primer, regenerated by consolidation.
    pub fn primer(&self, space: &SpaceId) -> PathBuf {
        self.facts(space).join("INDEX.md")
    }

    /// One topic's file.
    pub fn topic(&self, space: &SpaceId, topic: &TopicPath) -> PathBuf {
        self.facts(space).join(format!("{topic}.md"))
    }

    /// Facts awaiting confirmation.
    pub fn pending(&self, space: &SpaceId) -> PathBuf {
        self.space(space).join("pending")
    }

    /// CUA procedures (the cua area's format, the same metadata trailer).
    pub fn procedures(&self, space: &SpaceId) -> PathBuf {
        self.space(space).join("procedures")
    }

    /// The diffs of consolidation runs, with pre-images.
    pub fn consolidation(&self, space: &SpaceId) -> PathBuf {
        self.space(space).join("consolidation")
    }

    /// The rebuildable recall index (cache: deletable).
    pub fn index_db(&self, space: &SpaceId) -> PathBuf {
        self.cache_home
            .join("quire")
            .join("memory")
            .join(space.as_str())
            .join("index.db")
    }

    /// `<config>/quire/memory.toml`: the rule set, written only by memoryd.
    pub fn memory_toml(&self) -> PathBuf {
        self.config_home.join("quire").join("memory.toml")
    }

    /// Decrypted edit copies on tmpfs.
    pub fn edit(&self, space: &SpaceId) -> PathBuf {
        self.runtime_dir
            .join("quire")
            .join("memory")
            .join("edit")
            .join(space.as_str())
    }

    /// `path` relative to the data root, for tests and logs.
    pub fn relative_to_memory<'a>(&self, path: &'a Path) -> Option<&'a Path> {
        path.strip_prefix(self.memory()).ok()
    }
}
