//! `Store`: the facts of one Space over a vault. Frozen signatures; the bodies are `todo!()`
//! until the memfiles fill (FINDINGS.md).

use crate::topic::{ParseError, TopicFile};
use crate::vault::{Vault, VaultError, VaultPath};
use almanac_core::{
    Count, Fact, FactId, Link, PlanDigest, Settlement, SpaceId, TopicPath, UserText,
};
use jiff::tz::TimeZone;

/// Why a store operation failed.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum MemfilesError {
    /// The vault failed.
    #[error("vault: {0}")]
    Vault(#[from] VaultError),
    /// A file did not parse.
    #[error("{path}: {err}")]
    Parse {
        /// Which file.
        path: VaultPath,
        /// Why.
        err: ParseError,
    },
    /// The fact is not in `pending/`.
    #[error("not pending: {0}")]
    NotPending(FactId),
    /// No such topic.
    #[error("no such topic: {0}")]
    NoSuchTopic(TopicPath),
}

/// The primer, `facts/INDEX.md`: one line per topic, regenerated by consolidation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Primer {
    /// The topics, in order.
    pub entries: Vec<PrimerEntry>,
}

/// One line of the primer.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PrimerEntry {
    /// The topic.
    pub topic: TopicPath,
    /// Its title.
    pub title: UserText,
    /// A short summary.
    pub summary: UserText,
}

/// The primer is at most this many lines.
pub const PRIMER_MAX_LINES: usize = 200;

impl Primer {
    /// The markdown: a heading, a blank line, then `- [title](topic.md): summary` per entry,
    /// cut so the whole file is at most [`PRIMER_MAX_LINES`] lines.
    pub fn render(&self) -> String {
        let mut out = String::from("# Memory\n\n");
        for entry in self.entries.iter().take(PRIMER_MAX_LINES - 2) {
            out.push_str(&format!(
                "- [{}]({}.md): {}\n",
                entry.title.as_str(),
                entry.topic,
                entry.summary.as_str()
            ));
        }
        out
    }
}

/// The facts of one Space.
#[derive(Debug)]
pub struct Store<V: Vault> {
    vault: V,
    space: SpaceId,
    tz: TimeZone,
}

impl<V: Vault> Store<V> {
    /// A store over `vault` for `space`; dated headings use `tz`.
    pub fn new(vault: V, space: SpaceId, tz: TimeZone) -> Self {
        Self { vault, space, tz }
    }

    /// The Space.
    pub fn space(&self) -> &SpaceId {
        &self.space
    }

    /// The vault beneath.
    pub fn vault(&self) -> &V {
        &self.vault
    }

    /// The time zone of the headings.
    pub fn tz(&self) -> &TimeZone {
        &self.tz
    }

    /// Every topic that has a file.
    pub fn topics(&self) -> Result<Vec<TopicPath>, MemfilesError> {
        todo!("list `facts/`, strip `.md`, skip INDEX.md")
    }

    /// One topic file, parsed.
    pub fn read(&self, t: &TopicPath) -> Result<TopicFile, MemfilesError> {
        let _ = t;
        todo!("read, parse_topic; NoSuchTopic when the file is absent")
    }

    /// Appends a fact to a topic (creating the file): add-only, existing blocks unchanged.
    pub fn append(&self, t: &TopicPath, fact: Fact) -> Result<(), MemfilesError> {
        let _ = (t, fact);
        todo!("read or create, push Block::Fact, render_topic, write_atomic")
    }

    /// Puts a fact derived from untrusted text in `pending/` until the person keeps it.
    pub fn stage(&self, fact: Fact, topic: TopicPath) -> Result<(), MemfilesError> {
        let _ = (fact, topic);
        todo!("write `pending/<fact-id>.md` as a one-fact topic file")
    }

    /// The facts waiting for the person.
    pub fn pending(&self) -> Result<Vec<(TopicPath, Fact)>, MemfilesError> {
        todo!("list `pending/`, parse each")
    }

    /// Keeps or discards a pending fact. `Keep` carries the confirmation receipt, which only
    /// the shell's own UI path can mint.
    pub fn settle(&self, id: &FactId, settlement: Settlement) -> Result<(), MemfilesError> {
        let _ = (id, settlement);
        todo!(
            "Keep: declassify the label with the receipt and append to its topic; Discard: remove; NotPending otherwise"
        )
    }

    /// Every fact derived from `links`, transitively through `Link::Fact`.
    pub fn derived_from(&self, links: &[Link]) -> Result<Vec<FactId>, MemfilesError> {
        let _ = links;
        todo!("scan topics and pending; breadth-first over Link::Fact")
    }

    /// Removes facts; only with the digest of a plan that contains them.
    pub fn remove(&self, ids: &[FactId], plan: &PlanDigest) -> Result<Count, MemfilesError> {
        let _ = (ids, plan);
        todo!("drop the blocks from topic files and pending/, rewrite atomically")
    }

    /// Writes `facts/INDEX.md`.
    pub fn write_primer(&self, primer: &Primer) -> Result<(), MemfilesError> {
        let _ = primer;
        todo!("write_atomic(VaultPath::primer(), primer.render())")
    }
}
